Blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('log_in/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/urls.py
from django.urls import path
from app_blog import views

app_name = 'app_blog'
urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('create-blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('blog-details/<path:slug>', views.blog_details, name="blog_details"),
    path('liked/<pk>/', views.Liked, name="liked_post"),
    path('uliked/<pk>/', views.Unliked, name="unliked_post"),
    path('my-blog/', views.MyBlog.as_view(), name="myblog"),
    path('edit-blog/<pk>/', views.EditBlog.as_view(), name="edit_blog"),
]

app_login/urls.py
from django.urls import path
from app_login import views


app_name = 'app_login'
urlpatterns = [
    path('singup/', views.SingUp, name="singup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('change_profile/', views.ProfileChang, name="chngProfile"),
    path('password/', views.pass_change, name="pass_change"),
    path('pro_pic_add/', views.Profile_pic_add, name="pro_pic_add"),
    path('change-pro-pic/', views.Change_Profile, name="change_pro_pic")
]

app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True, null=True)

app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from app_login import models
from django.contrib.auth.models import User

class UserInfoform(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta: 
        model = User
        fields = ('username','email','password1','password2')

class UserChangeInfo(UserChangeForm):
    class Meta: 
        model = User
        fields = ('username','email', 'first_name', 'last_name', 'password')

class Profile_pic_add(forms.ModelForm):
    class Meta:
        model = models.Userprofile
        fields = ['profile_pic']

app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from app_login import forms

# Create your views here.
def SingUp(request):
    form = forms.UserInfoform()
    registered = False
    if request.method == 'POST':
        form = forms.UserInfoform(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {
        'form':form,
        'registered':registered
    }
    return render(request, 'app_login/singup.html', context=dict)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
    else:
        form = AuthenticationForm()
            
    return render(request, 'app_login/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request, 'app_login/profile.html', context={})

@login_required
def ProfileChang(request):
    current_user = request.user
    form = forms.UserChangeInfo(instance=current_user)
    if request.method == 'POST':
        form = forms.UserChangeForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = forms.UserChangeForm(request.POST, instance=current_user)
    return render(request, 'app_login/profile_change.html', context={'form':form})



@login_required
def pass_change(request):
    curren_user = request.user
    changed = False
    form = PasswordChangeForm(curren_user)
    if request.method == 'POST':
        form = PasswordChangeForm(curren_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True

    return render(request, 'app_login/pass_change.html', context={'form':form, 'changed':changed})

@login_required
def Profile_pic_add(request):
    form = forms.Profile_pic_add()
    if request.method == 'POST':
        form = forms.Profile_pic_add(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/pro_pic_add.html', context={'form':form})


@login_required
def Change_Profile(request):
    form = forms.Profile_pic_add(instance=request.user.user_profile)
    if request.method == 'POST':
        form = forms.Profile_pic_add(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/pro_pic_add.html', context={'form':form})

templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block content %}
    <h1>Log in: </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary btn-sm">Login</button>
    </form>

{% endblock %}

templates/app_login/pass_change.html
{% extends 'base.html' %}
{% block title_block %} change profile {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% if changed %}
<div class="alert alert-success">
    Password changed successfully!
</div>
{% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-warning btn-sm">Change</button>
    </form>

{% endblock %}

templates/app_login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} profile {% endblock %}
{% block content %}
    <h2>Upload Profile picture here: </h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Add</button>
    </form>
{% endblock %}

templates/app_login/profile.html
{% extends 'base.html' %}
{% block title_block %} profile {% endblock %}
{% block content %}
   
{% if user.user_profile %}
    <img src="/media/{{ user.user_profile.profile_pic }}" class="rounded-circle" width="100px">
    <br><br>
    <a href="{% url 'app_login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
    {% else %}
    <img src="/media/profile_pics/avatar.jpg" class="rounded-circle" width="100px"><br><br>
    <a href="{% url 'app_login:pro_pic_add' %}" class="btn btn-info btn-sm">Add Profile Pic</a>
    {% endif %}
    <br><br>
    <h2>Your profile</h2>
    <p>Username: {{user.username}}</p>
    <p>Email: {{user.email}}</p>
    <p>Name: {{user.first_name}} {{user.last_name}}</p>
    <a href="{% url 'app_login:chngProfile' %}" class="btn btn-warning btn-sm">Change Info</a>
{% endblock %}

templates/app_login/profile_change.html
{% extends 'base.html' %}
{% block title_block %} change profile {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-warning btn-sm">Change</button>
    </form>

{% endblock %}

templates/app_login/singup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New account {% endblock %}
{% block content %}
{% if registered %}
<div class="alert alert-success">
    Account created successfully! <a href="{% url 'app_login:login' %}">Login here..</a>
</div>
{% else %}
<h1>Create New account: </h1>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'app_login:login' %}">Login Here</a></p>
{% endif %}
{% endblock %}