Blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('log_in/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/urls.py
from django.urls import path
from app_blog import views

app_name = 'app_blog'
urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('create-blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('blog-details/<path:slug>', views.blog_details, name="blog_details"),
    path('liked/<pk>/', views.Liked, name="liked_post"),
    path('uliked/<pk>/', views.Unliked, name="unliked_post"),
    path('my-blog/', views.MyBlog.as_view(), name="myblog"),
    path('edit-blog/<pk>/', views.EditBlog.as_view(), name="edit_blog"),
]

app_login/urls.py
from django.urls import path
from app_login import views


app_name = 'app_login'
urlpatterns = [
    path('singup/', views.SingUp, name="singup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('change_profile/', views.ProfileChang, name="chngProfile"),
    path('password/', views.pass_change, name="pass_change"),
    path('pro_pic_add/', views.Profile_pic_add, name="pro_pic_add"),
    path('change-pro-pic/', views.Change_Profile, name="change_pro_pic")
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
    
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-left: 50px;">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="/media/logo.jpg" alt="MHR" width="80px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_login:singup' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_login:login' %}">Login</a>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @{{user.username}}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'app_blog:create_blog' %}">Upload Blog</a>
                <a class="dropdown-item" href="{% url 'app_blog:myblog' %}">My Blogs</a>
                <a class="dropdown-item" href="{% url 'app_login:profile' %}">Your Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'app_login:logout' %}">Log out</a>
              </div>
            </li> 
          </ul>
        </div>
      </nav>
      
      <div class="container" style="padding-top: 20px; padding-bottom: 50px;">
        {% block content %}

        {% endblock %}
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>