Blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('log_in/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/urls.py
from django.urls import path
from app_blog import views

app_name = 'app_blog'
urlpatterns = [
    path('',views.BlogList.as_view(),name='blog_list'),
    path('create-blog/', views.CreateBlog.as_view(), name='create_blog'),
    path('blog-details/<path:slug>', views.blog_details, name="blog_details"),
    path('liked/<pk>/', views.Liked, name="liked_post"),
    path('uliked/<pk>/', views.Unliked, name="unliked_post"),
    path('my-blog/', views.MyBlog.as_view(), name="myblog"),
    path('edit-blog/<pk>/', views.EditBlog.as_view(), name="edit_blog"),
]

app_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator


# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="what is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image", validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])
    publis_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publis_date',)

    def __str__(self):
        return self.blog_title
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)

    def __str__(self):
        return self.comment
    
class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

    def __str__(self):
        return self.user + "likes" + self.blog

app_blog/forms.py
from django import forms
from app_blog.models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

app_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.views.generic import CreateView, ListView, UpdateView, DetailView, TemplateView, View, DeleteView
from django.urls import reverse, reverse_lazy
from app_blog.models import Blog, Likes,Comment
from app_blog.forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import Http404
import uuid

# Create your views here.

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'app_blog/create_blog.html'
    fields = ('blog_title','blog_content','blog_image')

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        cleaned_title = ''.join(e for e in title if e.isalnum() or e == ' ')
        cleaned_title = cleaned_title.replace(' ', '-').lower()
        blog_obj.slug = cleaned_title + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class BlogList(LoginRequiredMixin, ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/blog_list.html'


@login_required 
def blog_details(request, slug):
    try:
        blog = Blog.objects.get(slug=slug)
        comment_form = CommentForm()
        already_liked = Likes.objects.filter(blog=blog, user=request.user)
        if already_liked:
            Liked = True
        else:
            Liked = False
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.user = request.user
                comment.blog = blog
                comment.save()
                return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':slug}))
    except Blog.DoesNotExist:
        raise Http404("Blog does not exist")
    return render(request, 'app_blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'Liked':Liked})


@login_required
def Liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':blog.slug}))

@login_required
def Unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':blog.slug}))

class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'app_blog/my_blogs.html'


class EditBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title','blog_content', 'blog_image')
    template_name = 'app_blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('app_blog:blog_details', kwargs={'slug':self.object.slug})

templates/app_blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h2>{{blog.blog_title}}</h2>
            <h4>Posted by: @{{blog.author}}</h4>
            <i><h6>Published on: {{blog.publis_date}}</h6></i>
            <i><h6>Updated: {{blog.update_date}}</h6></i>
            <h6>{{ blog.liked_blog.count }} Likes, {{blog.blog_comment.count}} comments</h6>
        </div>
        <div class="col-sm-6">
            <img src="/media/{{blog.blog_image}}" width="100%">
        </div>
        <p>{{blog.blog_content|linebreaks}}</p>
    </div>
    {% if not Liked %}
        <a href="{% url 'app_blog:liked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-up"></i></a>
    {% else %}
        <a href="{% url 'app_blog:unliked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-down"></i></a>
    {% endif %}
    <div class="row">
        <div class="col-sm-6">
            <hr>
            <h5>Comments:</h5>
            {% for comment in blog.blog_comment.all %}
                <p><a href="#">@{{comment.user}}</a> {{comment.comment}} <br> <i><h6>{{comment.comment_date}}</h6></i></p>
            {% endfor %}
        </div>
        <div class="col-sm-6">
            <form method="POST">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <button type="submit", class="btn btn-primary" btn-sm>comment</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/app_blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block content %}
{% for blog in blogs %}
    <h2>{{ blog.blog_title }}</h2>
    <h6><i>{{ blog.publis_date }}</i></h6>
    <div class="row">
        <div class="col-sm-4">
            <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
        </div>
        <div class="col-sm-8">
            <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a></p>
            <h6>Posted by: <a href="#">@{{blog.author}}</a></h6>
            <h6>{{blog.liked_blog.count}} <i class="fa-regular fa-thumbs-up"></i> {{blog.blog_comment.count}} <i class="fa-solid fa-comment"></i></h6>
        </div>
    </div>
{% endfor %}
{% endblock %}

templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create Blog {% endblock %}
{% block content %}
    <h2>Upload a Blog </h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success btn-sm">Upload</button>
    </form>
{% endblock %}

templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
    {% if blog.author == user %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-sm">Update</button>
        </form>
    {% else %}
        <p>You are not allowed to view this page: 404</p>
    {% endif %}
{% endblock %}

templates/app_blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{user}} {% endblock %}
{% block content %}
    {% for blog in user.post_author.all %}
        <h3>{{blog.blog_title}}</h3>
        <h6>{{blog.publis_date}}</h6>
        <div class="row">
            <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" width="100%">
            </div>
            <div class="col-sm-8">
                <p>{{blog.blog_content|range_filter|linebreaks}}</p>
                <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a>
            </div>
        </div>
        <a href="{% url 'app_blog:edit_blog' pk=blog.pk%}">Edit</a>
        <hr>
    {% endfor %}
{% endblock %}